package io.github.completionml.train

import io.github.completionml.core.lex.GoLanguage
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue

class PrepareTest {
    private val names = (1..300).map { "owner${it}__repo$it" }

    @Test fun foldsAreDeterministicAndOrderIndependent() {
        val a = Folds.assign(names, 30)
        val b = Folds.assign(names.shuffled(java.util.Random(1)), 30)
        assertEquals(a, b)
    }

    @Test fun foldSizes() {
        val a = Folds.assign(names, 30)
        assertEquals(30, a.values.count { it == Fold.TEST })
        assertEquals(90, a.values.count { it == Fold.RANK })
        assertEquals(180, a.values.count { it == Fold.LM })
    }

    @Test fun md5PrefixMatchesShellRecipe() {
        // printf '%s' abc | md5sum -> 900150983cd24fb0...
        assertEquals("90015098", Folds.md5Prefix("abc"))
    }

    @Test fun contentFilters() {
        assertEquals("binary", PrepareFilters.contentReason(byteArrayOf(0x70, 0, 0x71)))
        assertEquals("non_utf8", PrepareFilters.contentReason(byteArrayOf(0x70, 0x81.toByte(), 0x8d.toByte())))   // undefined in cp1252 too
        assertNull(PrepareFilters.contentReason(byteArrayOf(0x70, 0xff.toByte(), 0xfe.toByte())))                   // cp1252 "ÿþ" is accepted
        assertEquals("generated_marker", PrepareFilters.contentReason("// Code generated by protoc. DO NOT EDIT.\npackage x\n".toByteArray()))
        assertEquals("generated_marker", PrepareFilters.contentReason("// Autogenerated by tool\npackage x\n".toByteArray()))
        assertEquals("long_lines", PrepareFilters.contentReason(("package x\nvar d = \"" + "a".repeat(2000) + "\"\n").toByteArray()))
        assertNull(PrepareFilters.contentReason("package x\n\nfunc F() int { return 1 }\n".toByteArray()))
    }

    @Test fun generatedMarkerOnlyInComments() {
        assertTrue(Corpus.isGeneratedHead("// Code generated by protoc. DO NOT EDIT.\npackage x\n"))
        assertTrue(Corpus.isGeneratedHead("/*\n * Code generated by x\n * DO NOT EDIT\n */\npackage x\n"))
        assertTrue(Corpus.isGeneratedHead("// <auto-generated>\n//   tool\n// </auto-generated>\nclass A {}\n"))
        assertTrue(Corpus.isGeneratedHead("  /* <auto-generated */\nclass A {}\n"))
        // generator source that prints the marker from a string literal is real code
        assertFalse(Corpus.isGeneratedHead("package main\n\nvar header = `// Code generated by cgo -godefs; DO NOT EDIT.\n`\nfunc main() { fmt.Println(\"Code generated ... DO NOT EDIT\") }\n"))
        assertFalse(Corpus.isGeneratedHead("class A { string s = \"<auto-generated\"; }\n"))
        assertNull(PrepareFilters.contentReason("package main\n\nfunc main() {\n\tprintln(\"// Code generated by x. DO NOT EDIT.\")\n}\n".toByteArray()))
    }

    @Test fun csharpGeneratedCode() {
        // names and paths
        for (n in listOf("Form1.designer.cs", "Form1.Designer.cs", "AppDbContextModelSnapshot.cs", "Foo.AssemblyAttributes.cs", "Api.verified.cs", "Api.received.cs",
                         "TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs", "assemblyinfo.cs"))
            assertTrue(Corpus.isGeneratedName(n), n)
        for (n in listOf("Sdl.gen.cs", "Api.Generated.cs", "Thing.GENERATED.CS", "Report.approved.cs")) assertTrue(Corpus.isGeneratedName(n), n)
        for (n in listOf("MainWindow.xaml.cs", "Index.razor.cs", "Designer.cs", "DesignerHost.cs", "Snapshot.cs", "Generator.cs", "gen.cs", "Regen.cs")) assertFalse(Corpus.isGeneratedName(n), n)
        assertTrue(Corpus.isExcludedDir("Generated")); assertFalse(Corpus.isExcludedDir("Generators"))
        // v3 head markers: google-api, openapi-generator, decompilers, lower-case "do not edit"
        assertTrue(Corpus.isGeneratedHead("// Generated code. DO NOT EDIT!\nnamespace Google.Apis {}\n"))
        assertTrue(Corpus.isGeneratedHead("/*\n * Generated by: https://openapi-generator.tech\n */\nnamespace Org.OpenAPITools {}\n"))
        assertTrue(Corpus.isGeneratedHead("// Decompiled with JetBrains decompiler\n// Type: Foo.Bar\nnamespace Foo {}\n"))
        assertTrue(Corpus.isGeneratedHead("#region Assembly ILSpy\nnamespace Foo {}\n"))
        assertTrue(Corpus.isGeneratedHead("// This code was generated by a tool. Please do not edit.\nnamespace Foo {}\n") || PrepareFilters.contentReason("// This code was generated by a tool. Please do not edit.\nnamespace Foo {}\n".toByteArray()) == "generated_marker")
        assertFalse(Corpus.isGeneratedHead("// Please do not edit the generated SQL by hand; see docs.\nclass Migrator {}\n"))   // "do not edit" alone is not enough
        assertTrue(Corpus.isGeneratedPath("src/Data/Migrations/20240101123456_InitialCreate.cs"))
        assertTrue(Corpus.isGeneratedPath("Migrations/20240101123456_Init.cs"))
        assertFalse(Corpus.isGeneratedPath("src/Migrations/MigrationRunner.cs"))
        assertFalse(Corpus.isGeneratedPath("src/Migrations/2024_notes.cs"))
        // heads: BOM, AutoRest without DO NOT EDIT, AWS SDK, "lost if regenerated", GeneratedCode attribute, text before the marker
        assertTrue(Corpus.isGeneratedHead("﻿// <auto-generated />\nnamespace X {}\n"))
        assertTrue(Corpus.isGeneratedHead("// Code generated by Microsoft (R) AutoRest Code Generator.\n// Changes may cause incorrect behavior and will be lost if the code is regenerated.\nnamespace X {}\n"))
        assertTrue(Corpus.isGeneratedHead("/*\n * Copyright X\n *\n * Do not modify this file. This file is generated from the s3.normal.json service model.\n */\nusing System;\n"))
        assertEquals("generated_marker", PrepareFilters.contentReason("// This file was generated by a tool.\nnamespace X {}\n".toByteArray()))
        assertEquals("generated_marker", PrepareFilters.contentReason("﻿// This code was generated by Refit.\nnamespace X {}\n".toByteArray()))
        assertEquals("generated_marker", PrepareFilters.contentReason("using System.CodeDom.Compiler;\n[GeneratedCode(\"xsd\", \"4.8\")]\npublic partial class Order {}\n".toByteArray()))
        // hand-written code that mentions generation is kept
        assertNull(PrepareFilters.contentReason("// Generates code for the client.\nclass Generator { void Run() { Console.WriteLine(\"Code generated by me\"); } }\n".toByteArray()))
        assertNull(PrepareFilters.contentReason("using System;\n// Helper used by the generated clients.\nclass Util {}\n".toByteArray()))
        // encodings: cp1252 header is recovered, UTF-16 is not
        assertNull(PrepareFilters.contentReason("// © 2010 Acme\nclass A {}\n".toByteArray(Charsets.ISO_8859_1)))
        assertEquals("non_utf8", PrepareFilters.contentReason(byteArrayOf(0xff.toByte(), 0xfe.toByte(), 0x63, 0x6c)))
    }

    @Test fun selectionByStarsAndLimit() {
        val cat = mapOf("a__x" to (10 to "MIT"), "b__y" to (500 to "Apache-2.0"), "c__z" to (50 to "none"))
        val sel = selectRepos(listOf("a__x", "b__y", "c__z", "d__w"), cat, minStars = 20, maxRepos = 2)
        assertEquals(listOf("b__y", "c__z"), sel.map { it.dir })
        assertEquals("unknown", selectRepos(listOf("d__w"), cat, 0, 5).single().license)
    }

    @Test fun dedupFingerprintsMatchOffer() {
        val src = "package p\nfunc alpha(beta int) int { gamma := beta; delta := gamma; a1 := delta; a2 := a1; a3 := a2; a4 := a3; a5 := a4; return a5 + epsilon }\n"
        val d = Dedup(0.8)
        val t = GoLanguage.tokenizer.tokens(src)
        assertEquals(Dedup.Verdict.NEW, d.offer(d.fingerprint(t)))
        assertEquals(Dedup.Verdict.EXACT, d.offer(d.fingerprint(t)))
        val near = GoLanguage.tokenizer.tokens(src.replace("epsilon", "zeta"))
        assertNotNull(near)
        assertTrue(d.offer(d.fingerprint(near)) != Dedup.Verdict.NEW)
    }
}
