package io.github.completionml.train

import io.github.completionml.core.spi.MlLanguage
import java.io.File

/**
 * Source files of a language under `<data>/repos/<owner>__<repo>/...`, with generated/vendored files dropped and a
 * deterministic train/test split (by repository when there are enough of them, otherwise by file hash).
 */
class Corpus(val root: File, val language: MlLanguage, val splitBy: String = "auto", val testShare: Int = 10, includeList: File? = null) {
    class Source(val repo: String, val file: File)

    /** Repositories under `repos/`, optionally restricted to the directory names listed in [includeList] (one per line). */
    val repos: List<File> = run {
        val all = File(root, "repos").listFiles { f -> f.isDirectory }?.sortedBy { it.name } ?: emptyList()
        if (includeList == null) all else {
            val names = includeList.readLines().map { it.trim() }.filter { it.isNotEmpty() && !it.startsWith("#") }.toSet()
            val missing = names - all.map { it.name }.toSet()
            require(missing.isEmpty()) { "repos listed in $includeList but not cloned: $missing" }
            all.filter { it.name in names }
        }
    }

    fun files(): List<Source> = repos.flatMap { repo ->
        repo.walkTopDown()
            .onEnter { d -> d.name !in EXCLUDED_DIRS && d.name != ".git" && !isSymlink(d) }   // cloned repos are untrusted: never follow links out of the tree
            .filter { f -> f.isFile && !isSymlink(f) && language.extensions.any { f.name.endsWith(it) } && f.length() in 1..MAX_FILE_BYTES && !isGenerated(f) }
            .map { Source(repo.name, it) }
            .toList()
    }

    fun isTest(s: Source): Boolean {
        val by = if (splitBy == "auto") (if (repos.size >= 20) "repo" else "file") else splitBy
        val key = if (by == "repo") s.repo else s.repo + "/" + s.file.relativeTo(root).path.replace('\\', '/')
        val h = key.hashCode().toLong() and 0x7fffffffL
        return (h % 100) < testShare
    }

    private fun isSymlink(f: File) = java.nio.file.Files.isSymbolicLink(f.toPath())

    private fun isGenerated(f: File): Boolean {
        val n = f.name
        if (n.endsWith(".g.cs") || n.endsWith(".g.i.cs") || n.endsWith(".Designer.cs") || n.endsWith(".pb.go") || n.endsWith("_string.go") || n.endsWith(".generated.cs")) return true
        if (n.endsWith("AssemblyInfo.cs") || n.endsWith("GlobalUsings.cs")) return true
        // first 2 KB: auto-generated markers
        val head = ByteArray(2048)
        val read = f.inputStream().use { it.read(head) }
        if (read <= 0) return true
        val text = String(head, 0, read, Charsets.UTF_8)
        return text.contains("<auto-generated") || text.contains("Code generated") && text.contains("DO NOT EDIT")
    }

    companion object {
        const val MAX_FILE_BYTES = 1L shl 20
        val EXCLUDED_DIRS = setOf("bin", "obj", "vendor", "third_party", "external", "node_modules", "packages", "testdata")
    }
}
