package io.github.completionml.train

import io.github.completionml.core.lex.Languages
import io.github.completionml.core.spi.MlLanguage
import java.io.BufferedWriter
import java.io.File
import java.nio.ByteBuffer
import java.nio.charset.CharacterCodingException
import java.nio.charset.CodingErrorAction
import java.nio.file.Files
import java.security.MessageDigest
import java.util.concurrent.Callable
import java.util.concurrent.Executors
import java.util.concurrent.Future

/**
 * One-time corpus preparation: walks `<data>/repos`, filters files, deduplicates across the whole corpus and assigns repositories to
 * the cross-fitting folds. Writes `<data>/prepared/manifest.jsonl` (one line per file that was read) and `stats.json`;
 * source files are neither copied nor rewritten. Only `status == "ok"` manifest lines are training data.
 */
enum class Fold { LM, RANK, TEST;
    val id get() = name.lowercase()
}

class PrepareOptions(
    val language: MlLanguage,
    val data: File,
    val out: File = File(data, "prepared"),
    val catalog: File? = null,
    val dedupThreshold: Double = 0.8,        // <= 0 disables dedup
    val maxFileBytes: Long = 1L shl 20,
    val maxRepos: Int = Int.MAX_VALUE,
    val minStars: Int = 0,
    val maxFilesPerRepo: Int = Int.MAX_VALUE,
    val maxBytes: Long = Long.MAX_VALUE,     // total budget of kept (ok) bytes, split between folds by repository count
    val testRepos: Int = 30,
    val threads: Int = Runtime.getRuntime().availableProcessors(),
)

class RepoMeta(val dir: String, val stars: Int, val license: String, val inCatalog: Boolean)

object Folds {
    /**
     * Same recipe as `tools/server/sets.sh`: repositories ordered by `md5(name)[0..8]` (then name); the first [testRepos] are the held-out
     * test fold, of the rest every third one (1-based) is the ranker fold and the others the LM fold. Deterministic for a given set of names.
     */
    fun assign(names: Collection<String>, testRepos: Int): Map<String, Fold> {
        val ordered = names.map { md5Prefix(it) to it }.sortedWith(compareBy({ it.first }, { it.second })).map { it.second }
        val result = HashMap<String, Fold>()
        var trainIndex = 0
        for ((i, n) in ordered.withIndex()) {
            result[n] = if (i < testRepos) Fold.TEST else { trainIndex++; if (trainIndex % 3 == 0) Fold.RANK else Fold.LM }
        }
        return result
    }

    fun md5Prefix(s: String): String =
        MessageDigest.getInstance("MD5").digest(s.toByteArray()).take(4).joinToString("") { "%02x".format(it) }
}

/** Per-file filter decisions that need the file content (everything name/size-based lives in [Corpus]). */
object PrepareFilters {
    // a comment line whose first ~60 chars lead to a generated-code phrase ("// This file was generated by X", " * Do not modify ...")
    private val GENERATED_HEAD = Regex("""(?im)^﻿?\s*(//|/\*|\*|#)\s*.{0,60}?\b(autogenerated|auto-generated|automatically generated|this (file|code) (was|is|has been) (auto-?generated|generated)|generated (by|from|with) [a-z]|@generated)\b|@generated\b""")

    /** Decodes [bytes] as text: strict UTF-8, falling back to windows-1252 (C# headers with © / accents); null for UTF-16 or undecodable. */
    fun decodeText(bytes: ByteArray): String? {
        return try {
            Charsets.UTF_8.newDecoder().onMalformedInput(CodingErrorAction.REPORT).onUnmappableCharacter(CodingErrorAction.REPORT).decode(ByteBuffer.wrap(bytes)).toString()
        } catch (e: CharacterCodingException) {
            if (bytes.size >= 2 && (bytes[0] == 0xFF.toByte() && bytes[1] == 0xFE.toByte() || bytes[0] == 0xFE.toByte() && bytes[1] == 0xFF.toByte())) return null
            try { CP1252.newDecoder().onMalformedInput(CodingErrorAction.REPORT).onUnmappableCharacter(CodingErrorAction.REPORT).decode(ByteBuffer.wrap(bytes)).toString() }
            catch (e2: CharacterCodingException) { null }
        }
    }
    private val CP1252 = java.nio.charset.Charset.forName("windows-1252")

    /** null if the bytes are acceptable text, otherwise the drop reason. */
    fun contentReason(bytes: ByteArray, maxLineChars: Int = 1000, maxAvgLine: Int = 100): String? {
        for (b in bytes) if (b.toInt() == 0) return "binary"
        val text = decodeText(bytes) ?: return "non_utf8"
        return textReason(text, maxLineChars, maxAvgLine)
    }

    fun textReason(text: String, maxLineChars: Int = 1000, maxAvgLine: Int = 100): String? {
        val head = text.take(2048)
        if (Corpus.isGeneratedHead(head)) return "generated_marker"
        if (GENERATED_HEAD.containsMatchIn(head.take(1024))) return "generated_marker"
        if (head.contains("GeneratedCode(")) return "generated_marker"   // [GeneratedCode("tool", "1.0")] attribute
        var lines = 0; var maxLen = 0; var cur = 0
        for (c in text) { if (c == '\n') { lines++; if (cur > maxLen) maxLen = cur; cur = 0 } else cur++ }
        if (cur > 0) { lines++; if (cur > maxLen) maxLen = cur }
        if (maxLen > maxLineChars || lines > 0 && text.length / lines > maxAvgLine) return "long_lines"   // minified / embedded data
        return null
    }

    fun lineCount(text: String): Int { var n = 0; for (c in text) if (c == '\n') n++; return if (text.isNotEmpty() && !text.endsWith("\n")) n + 1 else n }
}

private class FileRecord(val path: String, val bytes: Long, val lines: Int, val tokens: Int, var status: String, val fp: Dedup.Fingerprint?)

/** Counters keyed by reason: [files, bytes]. */
private class Counters {
    val m = java.util.TreeMap<String, LongArray>()
    fun add(reason: String, bytes: Long, files: Long = 1) { val a = m.getOrPut(reason) { LongArray(2) }; a[0] += files; a[1] += bytes }
    fun merge(o: Counters) { for ((k, v) in o.m) add(k, v[1], v[0]) }
}

private class RepoScan(val meta: RepoMeta, val records: List<FileRecord>, val dropped: Counters, val candidates: Int, val excludedFiles: Long, val excludedBytes: Long)

private fun scanRepo(opt: PrepareOptions, meta: RepoMeta, root: File): RepoScan {
    val lang = opt.language
    val dropped = Counters()
    val candidates = ArrayList<File>()
    var exFiles = 0L; var exBytes = 0L
    val repoDir = File(root, "repos/${meta.dir}")
    fun hasExt(n: String) = lang.extensions.any { n.endsWith(it) }
    fun isLink(f: File) = Files.isSymbolicLink(f.toPath())
    repoDir.walkTopDown()
        .onEnter { d ->
            if (d != repoDir && Corpus.isExcludedDir(d.name)) {
                // not descended into, but counted (stat only) so that the stats show how much vendored code was left out
                if (d.name != ".git" && !isLink(d)) d.walkTopDown().onEnter { !isLink(it) }.filter { it.isFile && hasExt(it.name) }.forEach { exFiles++; exBytes += it.length() }
                false
            } else !isLink(d)
        }
        .filter { it.isFile && hasExt(it.name) }
        .forEach { f ->
            when {
                isLink(f) -> dropped.add("symlink", 0)
                else -> { val len = f.length()
                    when {
                        len == 0L -> dropped.add("empty", 0)
                        len > opt.maxFileBytes -> dropped.add("too_large", len)
                        Corpus.isGeneratedName(f.name) || Corpus.isGeneratedPath(f.relativeTo(repoDir).path.replace('\\', '/')) -> dropped.add("generated_name", len)
                        else -> candidates.add(f)
                    } }
            }
        }
    candidates.sortBy { it.path }
    val records = ArrayList<FileRecord>()
    var ok = 0
    val dedupFp = opt.dedupThreshold > 0
    for (f in candidates) {
        val rel = f.relativeTo(repoDir).path.replace('\\', '/')
        val bytes = try { NoAtimeReader.readAllBytes(f) } catch (e: java.io.IOException) { dropped.add("unreadable", 0); continue }
        if (ok >= opt.maxFilesPerRepo) { dropped.add("repo_file_cap", bytes.size.toLong()); continue }
        val reason = PrepareFilters.contentReason(bytes)
        if (reason != null) { records.add(FileRecord(rel, bytes.size.toLong(), 0, 0, reason, null)); continue }
        val text = PrepareFilters.decodeText(bytes) ?: String(bytes, Charsets.UTF_8)
        val tokens = lang.tokenizer.tokens(text)
        ok++
        records.add(FileRecord(rel, bytes.size.toLong(), PrepareFilters.lineCount(text), tokens.size, "ok", if (dedupFp) FP_DEDUP.get().fingerprint(tokens) else null))
    }
    return RepoScan(meta, records, dropped, candidates.size, exFiles, exBytes)
}

private val FP_DEDUP = ThreadLocal<Dedup>()   // each worker thread has its own Dedup instance used only for fingerprint() (pure)

private fun loadCatalog(f: File?): Map<String, Pair<Int, String>> {
    if (f == null || !f.isFile) return emptyMap()
    val name = Regex("\"full_name\": \"([^\"]*)\""); val stars = Regex("\"stars\": (\\d+)"); val lic = Regex("\"license\": (null|\"([^\"]*)\")")
    val m = HashMap<String, Pair<Int, String>>()
    f.forEachLine { l ->
        val n = name.find(l)?.groupValues?.get(1) ?: return@forEachLine
        m[n.replace("/", "__")] = (stars.find(l)?.groupValues?.get(1)?.toInt() ?: 0) to (lic.find(l)?.groupValues?.get(2)?.takeIf { it.isNotEmpty() } ?: "none")
    }
    return m
}

/** Repositories to process after `--min-stars` / `--max-repos` (stars desc, name asc). */
fun selectRepos(dirs: List<String>, catalog: Map<String, Pair<Int, String>>, minStars: Int, maxRepos: Int): List<RepoMeta> =
    dirs.map { RepoMeta(it, catalog[it]?.first ?: 0, catalog[it]?.second ?: "unknown", it in catalog) }
        .filter { it.stars >= minStars }
        .sortedWith(compareBy({ -it.stars }, { it.dir }))
        .take(maxRepos)

private fun js(s: String) = buildString {
    append('"')
    for (c in s) when { c == '"' -> append("\\\""); c == '\\' -> append("\\\\"); c < ' ' -> append("\\u%04x".format(c.code)); else -> append(c) }
    append('"')
}

fun prepare(opt: PrepareOptions): File {
    val t0 = System.currentTimeMillis()
    val allDirs = File(opt.data, "repos").listFiles { f -> f.isDirectory }?.map { it.name }?.sorted() ?: error("no repos/ under ${opt.data}")
    val catalog = loadCatalog(opt.catalog ?: File(opt.data.absoluteFile.parentFile, "catalog/${opt.language.id}-20.jsonl"))
    val selected = selectRepos(allDirs, catalog, opt.minStars, opt.maxRepos)
    val folds = Folds.assign(selected.map { it.dir }, opt.testRepos)
    log("${opt.language.id}: ${allDirs.size} repos on disk, ${catalog.size} in catalogue, ${selected.size} selected; folds " +
        Fold.entries.joinToString { f -> "${f.id} ${selected.count { folds[it.dir] == f }}" })
    val foldBudget = Fold.entries.associateWith { f ->
        if (opt.maxBytes == Long.MAX_VALUE) Long.MAX_VALUE else (opt.maxBytes.toDouble() * selected.count { folds[it.dir] == f } / selected.size.coerceAtLeast(1)).toLong()
    }
    // dedup priority: lm, rank, then test; within a fold the most-starred repository first (the original rather than its copies)
    val order = Fold.entries.flatMap { f -> selected.filter { folds[it.dir] == f } }
    opt.out.mkdirs()
    val dedup = if (opt.dedupThreshold > 0) Dedup(opt.dedupThreshold) else null

    class FoldTotals { var repos = 0; var reposWithData = 0; var files = 0L; var bytes = 0L; var lines = 0L; var tokens = 0L; var dupFiles = 0L; var dupBytes = 0L }
    val totals = Fold.entries.associateWith { FoldTotals() }
    val dropped = Counters()          // by reason, over files that were considered; "dup_*" and content reasons come from the consumer
    val repoBytes = ArrayList<Triple<String, Long, Long>>()   // repo, kept bytes, excluded (vendored) bytes
    val licenseRepos = java.util.TreeMap<String, LongArray>() // license -> [repos, kept bytes]
    var excludedFiles = 0L; var excludedBytes = 0L
    var reposNoCandidates = 0; var reposAllFiltered = 0; var reposBudgetSkipped = 0; var reposWithExcluded = 0
    val noGo = ArrayList<String>()
    val keptBytesByFold = Fold.entries.associateWith { 0L }.toMutableMap()
    var manifestLines = 0L

    val pool = Executors.newFixedThreadPool(opt.threads) { r -> Thread(r, "prepare").also { it.isDaemon = true } }
    val window = ArrayDeque<Pair<RepoMeta, Future<RepoScan>>>()
    val manifest = File(opt.out, "manifest.jsonl").bufferedWriter(Charsets.UTF_8, 1 shl 20)
    var submitted = 0; var done = 0; var lastLog = System.currentTimeMillis()
    var seenFiles = 0L; var seenBytes = 0L

    fun submit() {
        while (window.size < opt.threads * 3 && submitted < order.size) {
            val meta = order[submitted++]
            val fold = folds.getValue(meta.dir)
            // a fold whose budget is used up is not even read
            if (keptBytesByFold.getValue(fold) >= foldBudget.getValue(fold)) {
                window.addLast(meta to java.util.concurrent.CompletableFuture.completedFuture(RepoScan(meta, emptyList(), Counters(), -1, 0, 0)))
            } else window.addLast(meta to pool.submit(Callable {
                if (FP_DEDUP.get() == null) FP_DEDUP.set(Dedup(opt.dedupThreshold.coerceAtLeast(0.01)))
                scanRepo(opt, meta, opt.data)
            }))
        }
    }
    submit()
    try {
        while (window.isNotEmpty()) {
            val (meta, fut) = window.removeFirst()
            val scan = fut.get()
            submit()
            val fold = folds.getValue(meta.dir); val ft = totals.getValue(fold)
            ft.repos++
            dropped.merge(scan.dropped)
            excludedFiles += scan.excludedFiles; excludedBytes += scan.excludedBytes
            if (scan.excludedFiles > 0) reposWithExcluded++
            if (scan.candidates < 0) { reposBudgetSkipped++; done++; continue }
            if (scan.candidates == 0) { reposNoCandidates++; if (scan.records.isEmpty() && scan.dropped.m.isEmpty() && scan.excludedFiles == 0L) noGo.add(meta.dir) }
            var kept = 0L; var keptFiles = 0
            for (r in scan.records) {
                seenFiles++; seenBytes += r.bytes
                var status = r.status
                if (status == "ok") {
                    if (keptBytesByFold.getValue(fold) >= foldBudget.getValue(fold)) status = "budget"
                    else if (dedup != null && r.fp != null) when (dedup.offer(r.fp)) {
                        Dedup.Verdict.EXACT -> status = "dup_exact"
                        Dedup.Verdict.NEAR -> status = "dup_near"
                        Dedup.Verdict.NEW -> {}
                    }
                }
                if (status == "ok") {
                    ft.files++; ft.bytes += r.bytes; ft.lines += r.lines; ft.tokens += r.tokens; kept += r.bytes; keptFiles++
                    keptBytesByFold[fold] = keptBytesByFold.getValue(fold) + r.bytes
                } else {
                    dropped.add(status, r.bytes)
                    if (status.startsWith("dup")) { ft.dupFiles++; ft.dupBytes += r.bytes }
                }
                manifest.write("{\"repo\":${js(meta.dir)},\"path\":${js(r.path)},\"bytes\":${r.bytes},\"lines\":${r.lines},\"tokens\":${r.tokens},\"fold\":\"${fold.id}\",\"status\":\"$status\"}\n")
                manifestLines++
            }
            if (scan.candidates > 0 && keptFiles == 0) reposAllFiltered++
            if (keptFiles > 0) { ft.reposWithData++; licenseRepos.getOrPut(meta.license) { LongArray(2) }.let { it[0]++; it[1] += kept } }
            repoBytes.add(Triple(meta.dir, kept, scan.excludedBytes))
            done++
            val now = System.currentTimeMillis()
            if (now - lastLog > 30_000) {
                lastLog = now
                val sec = (now - t0) / 1000.0
                log("%d/%d repos, %,d files read, %.1f GB read (%.0f MB/s, %.0f files/s); kept %,d files".format(
                    done, order.size, seenFiles, seenBytes / 1e9, seenBytes / 1e6 / sec, seenFiles / sec, totals.values.sumOf { it.files }))
            }
        }
    } finally { manifest.close(); pool.shutdownNow() }

    val sec = (System.currentTimeMillis() - t0) / 1000.0
    // stats.json
    val sb = StringBuilder()
    fun counters(c: Counters) = c.m.entries.joinToString(",", "{", "}") { "${js(it.key)}:{\"files\":${it.value[0]},\"bytes\":${it.value[1]}}" }
    sb.append("{\n")
    sb.append("\"language\":${js(opt.language.id)},\"seconds\":${"%.1f".format(sec)},\"dedup_threshold\":${opt.dedupThreshold},\"max_file_bytes\":${opt.maxFileBytes},")
    sb.append("\"options\":{\"max_repos\":${if (opt.maxRepos == Int.MAX_VALUE) "null" else opt.maxRepos},\"min_stars\":${opt.minStars},\"max_files_per_repo\":${if (opt.maxFilesPerRepo == Int.MAX_VALUE) "null" else opt.maxFilesPerRepo},\"max_bytes\":${if (opt.maxBytes == Long.MAX_VALUE) "null" else opt.maxBytes},\"test_repos\":${opt.testRepos}},\n")
    sb.append("\"repos\":{\"on_disk\":${allDirs.size},\"in_catalog\":${selected.count { it.inCatalog }},\"selected\":${selected.size},\"not_selected\":${allDirs.size - selected.size},")
    sb.append("\"with_kept_files\":${totals.values.sumOf { it.reposWithData }},\"no_source_files\":$reposNoCandidates,\"all_files_filtered\":$reposAllFiltered,\"skipped_by_budget\":$reposBudgetSkipped,\"with_excluded_dirs\":$reposWithExcluded},\n")
    val keptFiles = totals.values.sumOf { it.files }; val keptBytes = totals.values.sumOf { it.bytes }
    sb.append("\"kept\":{\"files\":$keptFiles,\"bytes\":$keptBytes,\"lines\":${totals.values.sumOf { it.lines }},\"tokens\":${totals.values.sumOf { it.tokens }}},\n")
    val dupFiles = totals.values.sumOf { it.dupFiles }
    sb.append("\"dedup\":{\"files\":$dupFiles,\"exact\":${dedup?.exactDuplicates ?: 0},\"near\":${dedup?.nearDuplicates ?: 0},\"rate_of_deduped_candidates\":${"%.4f".format(dupFiles.toDouble() / (dupFiles + keptFiles).coerceAtLeast(1))}},\n")
    sb.append("\"dropped_by_reason\":${counters(dropped)},\n")
    sb.append("\"excluded_dirs\":{\"files\":$excludedFiles,\"bytes\":$excludedBytes},\n")
    sb.append("\"per_fold\":{" + Fold.entries.joinToString(",") { f -> val t = totals.getValue(f)
        "${js(f.id)}:{\"repos\":${t.repos},\"repos_with_data\":${t.reposWithData},\"files\":${t.files},\"bytes\":${t.bytes},\"lines\":${t.lines},\"tokens\":${t.tokens},\"dup_files\":${t.dupFiles},\"dup_bytes\":${t.dupBytes}}" } + "},\n")
    sb.append("\"licenses\":{" + licenseRepos.entries.sortedByDescending { it.value[1] }.joinToString(",") { "${js(it.key)}:{\"repos\":${it.value[0]},\"bytes\":${it.value[1]}}" } + "},\n")
    sb.append("\"top_repos_by_kept_bytes\":[" + repoBytes.sortedByDescending { it.second }.take(50).joinToString(",") { "{\"repo\":${js(it.first)},\"kept_bytes\":${it.second}}" } + "],\n")
    sb.append("\"top_repos_by_excluded_bytes\":[" + repoBytes.sortedByDescending { it.third }.take(30).joinToString(",") { "{\"repo\":${js(it.first)},\"excluded_bytes\":${it.third},\"kept_bytes\":${it.second}}" } + "],\n")
    sb.append("\"repos_without_source_files\":[" + noGo.take(50).joinToString(",") { js(it) } + "],\"repos_without_source_files_count\":${noGo.size},\n")
    sb.append("\"manifest_lines\":$manifestLines\n}\n")
    File(opt.out, "stats.json").writeText(sb.toString())

    log("prepared ${opt.language.id} in %.0f s -> ${opt.out}".format(sec))
    log("kept %,d files, %.2f GB, %,d tokens; read %,d files (%.1f GB) = %.0f MB/s".format(keptFiles, keptBytes / 1e9, totals.values.sumOf { it.tokens }, seenFiles, seenBytes / 1e9, seenBytes / 1e6 / sec.coerceAtLeast(0.001)))
    log("dedup: ${dedup ?: "off"}")
    log("dropped: " + dropped.m.entries.joinToString { "${it.key} ${it.value[0]} files/%.2f GB".format(it.value[1] / 1e9) } + "; excluded dirs $excludedFiles files/%.2f GB (not read)".format(excludedBytes / 1e9))
    for (f in Fold.entries) { val t = totals.getValue(f); log("fold ${f.id}: ${t.repos} repos (${t.reposWithData} with data), ${t.files} files, %.2f GB, ${t.dupFiles} dups".format(t.bytes / 1e9)) }
    return opt.out
}

internal fun prepareCommand(args: Map<String, String>) {
    val lang = Languages.byId(args["lang"] ?: "go")
    val data = File(args.getValue("data"))
    prepare(PrepareOptions(
        lang, data,
        out = args["out"]?.let { File(it) } ?: File(data, "prepared"),
        catalog = args["catalog"]?.let { File(it) },
        dedupThreshold = args["dedup"]?.toDouble() ?: 0.8,
        maxFileBytes = args["max-file-bytes"]?.toLong() ?: (1L shl 20),
        maxRepos = args["max-repos"]?.toInt() ?: Int.MAX_VALUE,
        minStars = args["min-stars"]?.toInt() ?: 0,
        maxFilesPerRepo = args["max-files-per-repo"]?.toInt() ?: Int.MAX_VALUE,
        maxBytes = args["max-bytes"]?.toLong() ?: Long.MAX_VALUE,
        testRepos = args["test"]?.toInt() ?: 30,
        threads = args["threads"]?.toInt() ?: Runtime.getRuntime().availableProcessors(),
    ))
}
